[package]
name = "music-player"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "*"
iced = {version= "*", features= ["smol", "image"]}
iced_audio = "*"
